apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyplanet.fullname" . }}
  labels:
    {{- include "pyplanet.labels" . | nindent 4 }}
type: Opaque
stringData:
  base.yaml: |-
{{ toYaml .Values.config.base | nindent 4 }}
  apps.yaml: |-
{{ toYaml .Values.config.apps | nindent 4 }}
